name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # Jab aap main branch par push karenge tabhi deploy hoga

jobs:
  web-deploy:
    name: 🎉 Deploying
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.ftpupload.net }}
        username: ${{ secrets.if0_42009499 }}
        password: ${{ secrets.TIger290503  }}
        server-dir: /htdocs/  # InfinityFree mein files htdocs ke andar honi chahiye
